#!/usr/bin/env bash

set -euxo pipefail

helm repo add argo https://argoproj.github.io/argo-helm
helm repo update

GITEA_HTTP_CLUSTER_IP=$(kubectl get -n default svc gitea-http -ojsonpath='{.spec.clusterIP}'
)
export GITEA_HTTP_CLUSTER_IP

[[ -n "$GITEA_HTTP_CLUSTER_IP" ]] && envsubst < "$DRAG_HOME/helm_vars/argocd/values.yaml" | helm upgrade --install argocd argo/argo-cd \
  --create-namespace \
  --namespace=argocd \
  --values - \
  --wait

envsubst < "$DRAG_HOME/helm_vars/dag/values.tpl.yaml" > "$DRAG_HOME/helm_vars/dag/values.yaml"

# Add/Update origin
pushd "$DRAG_HOME"
git config user.email "${GITEA_USER}@example.com"
git config user.name "${GITEA_USER}"
# rename to use the 
git remote add dev "http://host.docker.internal:30950/${GITEA_USER}/drag-stack.git"
git add .
git commit -a -m "Init DRAG"
git push dev "${DAG_TARGET_VERSION}"
popd 

envsubst < "$DRAG_HOME/k8s/dag/app.yaml" | kubectl apply -f -

argocd login --plaintext "${ARGOCD_SERVER_HOST}" \
  --insecure \
  --username "${ARGO_ADMIN_USER}" \
  --password="${ARGO_ADMIN_PASSWORD}"

argocd app sync --assumeYes --timeout=600 dag-apps

# wait for drone to be ready
kubectl rollout status -n drone deploy/drone --timeout=120s

# Patching Gitea with Drone IP for resolving
DRONE_SERVICE_IP="$(kubectl get svc -n drone drone -ojsonpath='{.spec.clusterIP}')"
export DRONE_SERVICE_IP
kubectl patch statefulset gitea -n default --patch "$(envsubst<$DRAG_HOME/k8s/gitea/patch.json)"

kubectl rollout status -n default statefulset gitea --timeout=30s